### ISSUE TITLE
Loading a non existing operator should return nil or nil, error

### ISSUE THREAD

**Issue by ripienaar** [synadia-io/jwt-auth-builder.go#10]
At present `Operators().Get("foo")` returns a new operator when `foo` doesnt exist.  Makes it hard to handle user input errors etc.

`Operators().Get()` should probably reutrn `(Operator, error)`

**Comment by aricart** [comment]
hummm - ok looking at the code, for get - it literally will return nil, if the operator is not there - I think you had a store where a `foo` operator existed? - there's actually a test testing for this:

https://github.com/synadia-io/jwt-auth-builder.go/blob/9d1dffca78fb970bd634a23230c7001d80752426/tests/operator_test.go#L9


Also - I know why the Get() doesn't return an error - when the auth provider initializes, it read all the operators there. This is actually probably a concern (maybe?) as you could be loading 1000s of them - we should chat about this - currently the entire tree is loaded.

**Comment by ripienaar** [comment]
hmm, this morning indeed I cant seem to repro this, so weird, will investigate more what it is I saw, will close for now
